theme: jekyll-theme-minimal
title: Indie Game Con
description: A repo to plan Indie Game Con 2019 with the leadership team with documentation, website, and other assets we'd like to share.
logo: /resources/indiegamecon_logo_s.png
